;;; sculpture-themes-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from sculpture-themes.el

(add-to-list 'custom-theme-load-path (if load-file-name (file-name-directory load-file-name) default-directory))


;;; Generated autoloads from sculpture-themes-dark-theme.el

(register-definition-prefixes "sculpture-themes-dark-theme" '("sculpture-themes-dark"))


;;; Generated autoloads from sculpture-themes-light-theme.el

(register-definition-prefixes "sculpture-themes-light-theme" '("sculpture-themes-light"))


;;; Generated autoloads from sculpture-themes-pastel-theme.el

(register-definition-prefixes "sculpture-themes-pastel-theme" '("sculpture-themes-pastel"))

;;; End of scraped data

(provide 'sculpture-themes-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; sculpture-themes-autoloads.el ends here
